### ISSUE TITLE
Scan hangs if host is lost in the middle of a long running task

### ISSUE THREAD

**Issue by kdelee** [quipucords/rho#477]
There appears to be a bug in ansible that will cause a scan to hang if a host is lost.

A bug needs to be filed in Anisble once we have reproducer using just ansible.

**Comment by kdelee** [comment]
Similar problems:
https://github.com/ansible/ansible/issues/13327
https://github.com/ansible/ansible/issues/18305


The async/poll feature was suggested for them to use:
http://docs.ansible.com/ansible/latest/playbooks_async.html

I'm trying it out but no luck as of yet.

This is my playbook:
```
---

- name: reproduce lost host task hang
  hosts: all
  strategy: free
  tasks:
    - name: Do something that takes time 1
      shell: "ping -c 30 localhost"
      async: 30
      poll: 10
# after the first task completes, I kill one of the machines
    - name: Do something that takes time 2
      shell: "for i in {1..10}; do echo $i && sleep 2; done;"
      async: 30
      poll: 10
    - name: Do something that takes time 1
      shell: "ping -c 30 localhost"
      async: 30
      poll: 10
    - name: Do something that takes time 3
      shell: "for i in {1..10}; do echo $i && sleep 2; done;"
      async: 30
      poll: 10
```
```

**Comment by kdelee** [comment]
Another possible work around is setting a number of seconds in a `ansible.cfg` that ssh should check for a connnection!

```ini
[ssh_connection]

ssh_args = -o ServerAliveInterval=n
```

Where `n` is between 1 and 255 and is the number of seconds to check that the server is alive

**Comment by kdelee** [comment]
It looks like either of these are possible work arounds, but the config file is least invasive and directly addresses the issue at hand, which is the case that we want to be able to continue even if we lose one host.

The async/poll more addresses when one host of several is stuck indefinitely actually doing something on a host (i.e. it is still alive).

With the follwoing `ansible.cfg` in the directory of execution:
```ini
#ansible.cfg
[ssh_connection]

ssh_args = -o ServerAliveInterval=10
```
And executing the following playbook:

```yml
---

- name: reproduce lost host task hang
  hosts: all
  strategy: free
  tasks:
    - name: Do something that takes time 1
      shell: "ping -c 30 localhost"
# after the first task completes, I kill one of the machines
    - name: Do something that takes time 2
      shell: "for i in {1..10}; do echo $i && sleep 2; done;"
    - name: Do something that takes time 3
      shell: "ping -c 30 localhost"
    - name: Do something that takes time 4
      shell: "for i in {1..10}; do echo $i && sleep 2; done;"

```

I get the following output when I kill a server when the 2nd long running task is happening (after the 1st one completes).

```bash
ansible-playbook -i hosts kill-host.yml 

PLAY [reproduce lost host task hang] *******************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [10.10.XXX.XXX]
ok: [localhost]

TASK [Do something that takes time 1] ******************************************************************
changed: [10.10.XXX.XXX]
changed: [localhost]

TASK [Do something that takes time 2] ******************************************************************
changed: [localhost]
fatal: [10.10.XXX.XXX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Timeout, server 10.10.XXX.XXX not responding.\r\n", "unreachable": true}

TASK [Do something that takes time 3] ******************************************************************
changed: [localhost]

TASK [Do something that takes time 4] ******************************************************************
changed: [localhost]
	to retry, use: --limit @/home/elijah/test/kill-host.retry

PLAY RECAP *********************************************************************************************
10.10.XXX.XXX              : ok=2    changed=1    unreachable=1    failed=0   
localhost                  : ok=5    changed=4    unreachable=0    failed=0   

```

Now the question is -- how do we ship this? Do we just tell users to put this in their global config file? Do we edit the file for them in the install process?

**Comment by kdelee** [comment]
Ok, even better news, we can use the variables `ansible_ssh_args` or `ansible_ssh_common_args` in playbooks or in inventories, the distiction being that `ansibles_ssh_common_args` *appends* to any user configured args, and `ansible_ssh_args` overwrites them.

i.e. instead of on the config file level, we can write in the playbook itself:

```
- name: with these args a host dying mid-task won't make my playbook hang
  hosts: all
  strategy: free
  vars:
      # this appends args to whatever other ones
      # the user may have set in their ansible cfg
      # alternatively we can overwrite them with
      # ansible_ssh_args
      ansible_ssh_common_args: '-o ServerAliveInterval=10'
```
